spring:
  application:
    name: backend-portfolio
  threads:
    virtual:
      enabled: true
server:
  port: 8080

groq:
  base-url: ${GROQ_BASE_URL:https://api.groq.com/openai/v1}
  api-keys: ${GROQ_API_KEYS:sample-api-key-1,sample-api-key-2}
