spring:
  application:
    name: backend-portfolio
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:defaultDB}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jooq:
    sql-dialect: POSTGRES
server:
  port: 8080

groq:
  base-url: ${GROQ_BASE_URL:https://api.groq.com/openai/v1}
  api-keys: ${GROQ_API_KEYS:sample-api-key-1,sample-api-key-2}
